# 4.1 numpy ndarray : 다차원 배열 객체

In [5]:
import numpy as np

In [6]:
data = np.random.randn(2,3)

In [7]:
data

array([[-0.1562912 , -0.7448927 ,  0.88193836],
       [ 0.18747311, -1.08716467,  0.46706054]])

In [8]:
data * 10

array([[ -1.56291197,  -7.44892704,   8.8193836 ],
       [  1.87473108, -10.87164666,   4.67060535]])

In [9]:
data + data

array([[-0.31258239, -1.48978541,  1.76387672],
       [ 0.37494622, -2.17432933,  0.93412107]])

ndarray는 같은 종류의 데이터를 담을 수 있는 포괄적인 다차원 배열이다. ndarray의 모든 원소는 같은 자료형이어야 한다.
모든 배열은 각 차원의 크기를 알려준느 shape라는 튜플과 배열에 저장된 자료형을 알려주는 dtype이라는 객체를 가지고 있다.

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data1 = [6,7.5,8,0,1]

In [13]:
arr1 = np.array(data1)

In [14]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [16]:
arr2 = np.array(data2)

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr.ndimz

NameError: name 'arr' is not defined

In [19]:
arr.ndim

NameError: name 'arr' is not defined

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np,zeros((3,6))

NameError: name 'zeros' is not defined

In [24]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [26]:
np.zeros((2,3,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [30]:
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [33]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [36]:
np.empty((2,3))

array([[0.31258239, 1.48978541, 1.76387672],
       [0.37494622, 2.17432933, 0.93412107]])

In [37]:
np.empty((2,3))

array([[0.31258239, 1.48978541, 1.76387672],
       [0.37494622, 2.17432933, 0.93412107]])

In [38]:
np.empty((1,3))

array([[0., 0., 0.]])

In [40]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
np.arrange(15)

AttributeError: module 'numpy' has no attribute 'arrange'

In [42]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [44]:
arr2 = np.array([1,2,3],dtype=np.int64)

In [45]:
arr1.dtype

dtype('float64')

In [46]:
arr2.dtype

dtype('int64')

In [47]:
arr= np.array([1,2,3,4,5])

In [48]:
arr.dtype

dtype('int64')

In [49]:
float_arr =arr.astype(np.float64)

In [50]:
float_arr.dtype

dtype('float64')

In [51]:
float_arr

array([1., 2., 3., 4., 5.])

In [52]:
arr=np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [53]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [54]:
arr.dtype

dtype('float64')

In [56]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [57]:
numeric_strinsg= np.array(['1.25','-9.6','42'], dtype=np.string_)

In [58]:
numeric_strinsg

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [59]:
numeric_strinsg.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [60]:
int_array = np.arange(10)

In [61]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
calibers = np.array([.22,.270,.357], dtype =np.float64)

In [63]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
empty_uint32 = np.empty(8, dtype='u4')

In [65]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

4.1.3 numpyt 배열의 산술 연산

배열의 중요한 특징은 for 문을 작성하지 않고 데이터를 일괄 처리 할수 있다는 것ㄷ이다. 
이를 벡터화 라고 하는데, 가튼 크기으 ㅣ배열간의 산술연사은 배열으 ㅣ각 원소 단위로 적용된다

In [66]:
arr = np.array([[1,2,3],[4,5,6]])

In [67]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [69]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [70]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [71]:
arr **0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [72]:
arr2 = np.array([[0,4,1],[7,2,12]])

In [73]:
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [74]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

4.1.4 색인과 슬라이싱 기초

In [75]:
arr = np.arange(10)

In [76]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr[5]

5

In [78]:
arr[5:8]

array([5, 6, 7])

In [79]:
arr[5:8] =12

In [80]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [81]:
arr_slice = arr[5:8]

In [82]:
arr_slice

array([12, 12, 12])

In [83]:
arr_slice[1]=12345

In [84]:
arr_slice

array([   12, 12345,    12])

In [85]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [88]:
arr_slice[:]=64

In [89]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [90]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [91]:
arr2d[2]

array([7, 8, 9])

In [92]:
arr2d[0][2]

3

In [93]:
arr2d[0,2]

3

In [94]:
arr2d[1,2]

6

In [95]:
arr3d =np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]]])

In [96]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [97]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
arr3d[0,1]

array([4, 5, 6])

In [99]:
arr3d[0,0]

array([1, 2, 3])

In [100]:
old_values=arr3d[0].copy()
arr3d[0] =42

In [101]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [102]:
arr3d[0] = old_values

In [103]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [104]:
arr3d[1,0]

array([7, 8, 9])

In [105]:
x = arr3d[1]

In [106]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [107]:
x[0]

array([7, 8, 9])

In [108]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [111]:
arr2d[1,:2]

array([4, 5])

In [112]:
arr2d[:2,2]

array([3, 6])

In [113]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [114]:
arr2d[:2,1:] =0

In [115]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [122]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [123]:
data = np.random.randn(7,4)

In [124]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [125]:
data

array([[ 1.10151329,  0.7169402 , -0.88728717,  0.48416914],
       [ 0.29363845, -0.90722967, -0.78328555, -1.67582329],
       [-1.62891358,  0.79774202, -0.63282516,  0.61884087],
       [ 0.19962363,  0.13834266,  0.23480594, -1.29014108],
       [-0.79749144,  0.3745398 ,  0.58571365,  0.72681973],
       [-1.38697351,  1.00908024,  0.12416634,  1.86018006],
       [-0.29277223, -0.588489  ,  1.97108213,  0.06954094]])

In [126]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [128]:
data[names == 'Bob']

array([[ 1.10151329,  0.7169402 , -0.88728717,  0.48416914],
       [ 0.19962363,  0.13834266,  0.23480594, -1.29014108]])

In [130]:
data[names == 'Bob',2:]

array([[-0.88728717,  0.48416914],
       [ 0.23480594, -1.29014108]])

In [131]:
data[names == 'Bob',3]

array([ 0.48416914, -1.29014108])

In [132]:
names !='Bob'

array([False,  True,  True, False,  True,  True,  True])

In [133]:
data[~(names =='Bob')]

array([[ 0.29363845, -0.90722967, -0.78328555, -1.67582329],
       [-1.62891358,  0.79774202, -0.63282516,  0.61884087],
       [-0.79749144,  0.3745398 ,  0.58571365,  0.72681973],
       [-1.38697351,  1.00908024,  0.12416634,  1.86018006],
       [-0.29277223, -0.588489  ,  1.97108213,  0.06954094]])

In [134]:
cond = names=='Bob'

In [135]:
data[~cond]

array([[ 0.29363845, -0.90722967, -0.78328555, -1.67582329],
       [-1.62891358,  0.79774202, -0.63282516,  0.61884087],
       [-0.79749144,  0.3745398 ,  0.58571365,  0.72681973],
       [-1.38697351,  1.00908024,  0.12416634,  1.86018006],
       [-0.29277223, -0.588489  ,  1.97108213,  0.06954094]])

In [138]:
mask = (names =='Bob') | (names =='Will')

mask

In [139]:
mask

array([ True, False,  True,  True,  True, False, False])

In [140]:
data[mask]

array([[ 1.10151329,  0.7169402 , -0.88728717,  0.48416914],
       [-1.62891358,  0.79774202, -0.63282516,  0.61884087],
       [ 0.19962363,  0.13834266,  0.23480594, -1.29014108],
       [-0.79749144,  0.3745398 ,  0.58571365,  0.72681973]])

In [141]:
data[data<0] = 0

In [142]:
data

array([[1.10151329, 0.7169402 , 0.        , 0.48416914],
       [0.29363845, 0.        , 0.        , 0.        ],
       [0.        , 0.79774202, 0.        , 0.61884087],
       [0.19962363, 0.13834266, 0.23480594, 0.        ],
       [0.        , 0.3745398 , 0.58571365, 0.72681973],
       [0.        , 1.00908024, 0.12416634, 1.86018006],
       [0.        , 0.        , 1.97108213, 0.06954094]])

In [143]:
data[names !='Joe'] = 7

In [144]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.29363845, 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.00908024, 0.12416634, 1.86018006],
       [0.        , 0.        , 1.97108213, 0.06954094]])

4.1.6 팬시 색인

fancy indexing은 정수 배열을 사용한 색인을 설명하기 위해 Numpy에서 차용한 단어다.

In [152]:
arr = np.empty((8,4))

In [153]:
for i in range(8):
    arr[i] = i

In [155]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [156]:
arr[[4,3,2,1]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [2., 2., 2., 2.],
       [1., 1., 1., 1.]])

In [157]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [158]:
arr=np.arange(32).reshape((8,4))

In [159]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [160]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [161]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

4.1.7 배열전치와 축 바꾸기

In [162]:
arr = np.arange(15).reshape((3,5))

In [163]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [164]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [165]:
arr.np.random.randn(6,3)

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [166]:
arr= np.random.randn(6,3)

In [167]:
arr

array([[-0.22445139,  1.80354734,  1.92100498],
       [ 1.14041577,  0.12291071,  0.05387873],
       [-0.43473875, -0.66920207, -0.64499091],
       [-1.05664823, -1.002668  , -0.43262521],
       [-0.47117959,  0.76688874, -0.39715788],
       [-1.17902877,  0.24279066,  0.59540751]])

In [168]:
np.dot(arr.T,arr)

array([[ 4.26854885,  0.43815655, -0.14706277],
       [ 0.43815655,  5.36813022,  4.17663788],
       [-0.14706277,  4.17663788,  4.80858537]])

In [169]:
arr = np.arange(16).reshape((2,2,4))

In [170]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [172]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [173]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [176]:
arr.transpose((2,0,1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [177]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [178]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])