# 4.2 유니버셜 함수 : 배열의 각 원소를 빠르게 처리하는 함수

In [2]:
import numpy as np

유니버셜 함수는 하나 이상의 스칼라 값을 받아서 하나이상의 스칼라 결과값을 반환하는 간단한 함수를 고속으로 수행할 수있는 벡터화된 래퍼함수라고 생각

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [7]:
x = np.random.randn(8)

In [8]:
y = np.random.randn(8)

In [9]:
x

array([ 0.86483829,  0.12496354,  0.15100439, -0.25615285, -0.2439939 ,
       -1.39164707,  0.63334409,  0.59498086])

In [10]:
y

array([ 1.23148445, -0.00788482, -0.51301679, -1.36280569, -0.85737758,
        0.20581132, -1.23199119, -0.93369097])

In [11]:
np.maximum(x,y)

array([ 1.23148445,  0.12496354,  0.15100439, -0.25615285, -0.2439939 ,
        0.20581132,  0.63334409,  0.59498086])

In [12]:
arr =np.random.randn(7) * 5

In [13]:
arr

array([-7.92370735,  0.36242051, -3.64999565,  0.37041464,  1.94881431,
        0.92477296, -6.61929487])

In [14]:
remainder, whole_part = np.modf(arr) #np의 modf함수는 분수를 받아서 몫과 나머지를 반환함

In [15]:
remainder 

array([-0.92370735,  0.36242051, -0.64999565,  0.37041464,  0.94881431,
        0.92477296, -0.61929487])

In [16]:
whole_part

array([-7.,  0., -3.,  0.,  1.,  0., -6.])

In [17]:
arr

array([-7.92370735,  0.36242051, -3.64999565,  0.37041464,  1.94881431,
        0.92477296, -6.61929487])

In [18]:
np.sqrt(arr)

/Users/kimwaterman/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 0.60201371,        nan, 0.60861699, 1.3959994 ,
       0.96165116,        nan])

In [19]:
np.sqrt(arr,arr)

/Users/kimwaterman/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 0.60201371,        nan, 0.60861699, 1.3959994 ,
       0.96165116,        nan])